[package]
name = "engine"
version = "0.1.0"
edition = "2021"

[dependencies.glfw]
version = "*"

[dependencies.gl]
version = "0.6.0"

[dependencies.glam]
version = "0.22"

[dependencies.stb]
version = "0.3.2"