
symbol = '@'

[diet]
meat = false
plants = true
light = true

[body]
max_health = 1.0
max_nutrition = 1.0

smelliness = 1.0
strength = 1.0

[behavior]
awareness = 1.0
curiosity = 0.5
friendliness = 0.0